### ISSUE TITLE
My items are disappearing after I log out and log back in

### ISSUE THREAD

**Issue by jsimplicio** [hoodiehq/hoodie-app-tracker#19]
I just made a test account, added some items to the tracker and logged out. When I logged back in the items were gone without me ever clearing or deleting them. I try adding more things and logging back out and in again, and the same thing happened.

**Comment by stehuebn** [comment]
I've noticed a similar behaviour on every page reload testing the new app tracker on IE11 (Win8). The items list was empty but in DOM the tr tags exist. It wasn't necessary to log out/in. But after resizing the IE window for checking the responsive media css conditions the stored items suddenly appeared. Strange!

**Comment by jsimplicio** [comment]
@stehuebn You mean in the DOM there is a `<tr>` which has things in it but it shows as an empty table?

**Comment by jsimplicio** [comment]
@gr2m wanna take a look at this? To replicate issue, make a new account, add items log out and log back in, items will be gone.

**Comment by gr2m** [comment]
will do

**Comment by stehuebn** [comment]
@jsimplicio Yes! I just checked the DOM using the IE developer tools. I found some `<tr>` tags in the `<tbody class="list"....>` area but I couldn't see the items on screen.

Somehow the IE11 has problems to interprete the css expression correctly:
`
[data-store-state='empty'] .items,
[data-store-state='not-empty'] .items {
  display: block;
}
`
Sorry for my late reply!

**Comment by jsimplicio** [comment]
@stehuebn This is very weird and I can't really test it because I'm on a mac. I wonder why IE 11 is having trouble interpreting that... Because when you change window sizes they reappear on the screen correct?

**Comment by nickcolley** [comment]
I'll try to check this out.
@jsimplicio I run Linux but what I do is run IE in a VM. You can get IE VMs for mac here: https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/

Hope that helps.

**Comment by jsimplicio** [comment]
thanks @nickcolley try to replicate this and let me know.

**Comment by gr2m** [comment]
thanks @nickcolley for looking into this :+1: ping me if I can assist in any way

**Comment by jsimplicio** [comment]
Is this fixed now?

**Comment by nickcolley** [comment]
@jsimplicio I did try this out and it's very mysterious, I was going to try rendering the table without table markup but ran out of time.

**Comment by jsimplicio** [comment]
@nickcolley I don't know what is going on and if it's the table itself but this completely breaks the app for me. It's not saving the items I'm adding to the table once I logged off and log back in they are no longer on the table.

**Comment by gr2m** [comment]
can someone of you describe the exact steps to reproduce the problem?

**Comment by jsimplicio** [comment]
I believe my issue is different from @stehuebn's.

Make a new account, login with that account, add some items to the table and log out. Upon logging back in the items should disappear. I tried and added items again but every time I log off and back in they disappear.

**Comment by gr2m** [comment]
Okay I will look into this more closely as soon as possible, but probably won’t have time before Thursday

**Comment by jsimplicio** [comment]
update: This is only happening in my local environment. The app works for me at http://tracker.hood.ie

**Comment by gr2m** [comment]
@jsimplicio can you do `rm -rf node_modules && npm install` locally, and try again? Maybe the issue is resolved with one of the updates to the internal Hoodie modules

**Comment by gr2m** [comment]
I’m pretty sure that this is resolved now

**Comment by nickcolley** [comment]
@gr2m have you tested the IE issue?

**Comment by gr2m** [comment]
@nickcolley sorry I can’t recall an IE issue? If there is one, can you make a follow up issue? Please make sure you have the latest version of everything

**Comment by stehuebn** [comment]
@gr2m @nickcolley Hello, I just updated the Tracker via `rm -rf node_modules && npm install` and tested the problem described in the second post. The IE issue still exists (Win7/IE11), I think...

**Comment by gr2m** [comment]
okay thanks for checking @stehuebn! I’ll reopen the issue, something is still wrong here

**Comment by sdvg** [comment]
I can reproduce the IE11 issues. The elements appear one by one when i inspect them in F12 tools.

**Comment by gr2m** [comment]
I’ve just recently fixed an issue but it has not yet been deployed to https://tracker.hood.ie/. Can you reproduce the problem locally? Did you try a fresh install of the app (`rm -rf node_modules && npm install`)?

**Comment by sdvg** [comment]
Yes, I can reproduce the issue locally with fresh installed packages on a Windows 10 virtual machine.

**Comment by sdvg** [comment]
When I remove the following lines of CSS for test purposes the issue is gone:

```css
.items {
  display: none;
}
[data-store-state='empty'] .items,
[data-store-state='not-empty'] .items {
  display: block;
}
```

**Comment by gr2m** [comment]
can you tell the exact steps you take? Do you see any error in the console?

**Comment by sdvg** [comment]
I load the tracker page. Table and "Clear tracked items" button are both not visible.
There are no errors in the console.

**Comment by gr2m** [comment]
ah gotcha so it might be a CSS issue with the `[data-store-state='empty'] .items` selector? But IE 11 should have full support for that: http://caniuse.com/#feat=css-sel3

Can you check if the `data-store-state` attribute is set? It’s happening in these lines: https://github.com/hoodiehq/hoodie-app-tracker/blob/master/public/assets/js/index.js#L100-L104
